### GET api V1
GET http://localhost:5500/api/v1

### GET
GET http://localhost:5500/

### GET pessoas
GET http://localhost:5500/api/v1/pessoas

### POST pessoas
POST http://localhost:5500/api/v1/pessoas
Content-Type: application/json

{
  "nome": "Bruce MacQueen",
  "email": "bruce@gmail.com",
  "telefone": "001-124-2111",
  "organizacao": null,
  "tags": [
    "cinema",
    "amigos"
  ]
}

### GET organizacoes
GET http://localhost:5500/api/v1/organizacoes